[package]
name = "rsearch"
version = "0.1.0"
authors = ["daniel-whitfield-spotcap <daniel.whitfield@spotcap.com>"]

[dependencies]
rand = "*"
bio = "*"
itertools = "*"
clap = { version = "2.31", features = ["yaml"] }
